# Installation pandas

In [1]:
from idlelib.squeezer import Squeezer

from jupyter_core.troubleshoot import subs
from tornado.escape import squeeze

pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ------- -------------------------------- 1.8/9.9 MB 15.7 MB/s eta 0:00:01
   --------------------- ------------------ 5.2/9.9 MB 15.3 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.9 MB 15.9 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 14.9 MB/s  0:00:00
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.3 tzdata-2026.3
Note: you may need to restart the kernel to use updated packages.

# importing the pandas

In [2]:
import pandas as pd

## pandas series

In [4]:
#Strings

import numpy as np
import pandas as pd

Counters = ['india','pakistan','usa','srilanka']

print(pd.Series(Counters))

0       india
1    pakistan
2         usa
3    srilanka
dtype: str

In [5]:
marks = [93,63,76,98]
subject = ['science','maths','Telugu','Social']

print(pd.Series(marks,index=subject,name='Mahesh_markList'))

science    93
maths      63
Telugu     76
Social     98
Name: Mahesh_markList, dtype: int64

Series from Dict

In [7]:
marks = {
    'maths':93,
    'science':63,
    'Telugu':76,
    'Social':98
}

marks_Series = pd.Series(marks,name='Mahesh_markList')
print(marks_Series)

maths      93
science    63
Telugu     76
Social     98
Name: Mahesh_markList, dtype: int64

# Series Attribute

In [9]:
#Size
marks_Series.size

4

In [10]:
#dtype

marks_Series.dtypes

dtype('int64')

In [11]:
#Name

marks_Series.name

'Mahesh_markList'

In [12]:
#is_unique

marks_Series.is_unique

True

In [14]:
#Index

marks_Series.index

Index(['maths', 'science', 'Telugu', 'Social'], dtype='str')

In [15]:
#Index

marks_Series.index

Index(['maths', 'science', 'Telugu', 'Social'], dtype='str')

# Series using to read CSV file

# Read CSV

In [5]:
#With one Col

#pd.read_csv("C:\Users\rahul\Desktop\CampusX\subs.csv")

import pandas as pd

subs = pd.read_csv(r"C:\Users\rahul\Desktop\CampusX\subs.csv")


print(type(subs))

<class 'pandas.DataFrame'>

In [33]:
import pandas as pd

subs = pd.read_csv(r"C:\Users\rahul\Desktop\CampusX\subs.csv").squeeze("columns")
type(subs)
print(subs)
subs.head()

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

0    48
1    57
2    40
3    43
4    44
Name: Subscribers gained, dtype: int64

In [66]:
runs = pd.read_csv(r"C:\Users\rahul\Desktop\CampusX\kohli_ipl.csv").squeeze('columns')
runs
type(runs)

pandas.DataFrame

In [19]:
import pandas as pd

runs = pd.read_csv(r"C:\Users\rahul\Desktop\CampusX\kohli_ipl.csv", index_col="match_no").squeeze("columns")
type(runs)
runs

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [41]:
movie = pd.read_csv(r"C:\Users\rahul\Desktop\CampusX\bollywood.csv",index_col ='movie').squeeze('columns')
movie.head()
movie.tail()

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: str

In [43]:
runs.head(3)

   match_no  runs
0         1     1
1         2    23
2         3    13

In [44]:
runs.tail(5)

     match_no  runs
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

In [48]:
#SAMPLE : Randomly selecting movies

movie.sample(6)

movie
Khakee                 Amitabh Bachchan
Insaaf: The Justice          Dino Morea
Baaghi 2                   Tiger Shroff
Gunday                    Ranveer Singh
Ek Alag Mausam              Nandita Das
Phir Milenge                Salman Khan
Name: lead, dtype: str

In [49]:
##Value_Counts --> Movies

movie.value_counts()

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Tanishaa Mukerji     1
Tanuja               1
Ankit                1
Rakhee Gulzar        1
Edwin Fernandes      1
Name: count, Length: 566, dtype: int64

In [59]:
#Sort_Values
top_value = runs.sort_values("runs", ascending=False).head().values[0]
print(top_value)

[128 113]

In [60]:
runs

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [65]:
#inplace -->make prement changes in arrays

runs.sort_values("runs", inplace=True)
print(runs)

     match_no  runs
7           8     0
86         87     0
92         93     0
90         91     0
205       206     0
..        ...   ...
163       164   100
119       120   100
122       123   108
125       126   109
127       128   113

[215 rows x 2 columns]

In [67]:
runs

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

#Sort index --> inplace --> movie

In [68]:
movie.sort_index()

movie
1920 (film)                   Rajniesh Duggall
1920: London                     Sharman Joshi
1920: The Evil Returns             Vicky Ahuja
1971 (2007 film)                Manoj Bajpayee
2 States (2014 film)              Arjun Kapoor
                                   ...
Zindagi 50-50                      Veena Malik
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi Tere Naam           Mithun Chakraborty
Zokkomon                       Darsheel Safary
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Name: lead, Length: 1500, dtype: str